Check if diff is empty or not.
mildas/content-test-filtering pull request #31
Opened 2022-04-13 15:44 UTC by ggbecker

Fixes #30

2022-06-03 13:11 UTC, mildas requested changes
Let's avoid this +1 level of indentation of whole code block.

2022-06-03 13:11 UTC, mildas commented on ctf/analysis/JinjaAnalysis.py
> +                    change["starting_line"] = change["starting_line"] + 1
```suggestion
        if not diff:
            return changes
        for line in diff.split("\n"):
            if re.match(r"^(\+{3}|-{3})\s", line):
                continue
            m = re.match(r"@@\s-(.+)\s\+(.+)\s@@", line)
            if m:
                change = {"changed_lines": []}
                diff_lines = m.group(2).split(",")
                change["starting_line"] = int(diff_lines[0])
                if len(diff_lines) > 1:
                    change["number_of_lines"] = int(diff_lines[1])
                else:
                    change["number_of_lines"] = 1
                changes.append(change)
                continue
            m = re.match(r"^(?:\+|-)(.*)$", line)
            if m:
                change["changed_lines"].append(m.group(1))
            elif not change["changed_lines"]:  # First lines at unidiff are not changed
                change["starting_line"] = change["starting_line"] + 1
```

2022-06-03 15:16 UTC, ggbecker commented
@mildas updated

2022-06-07 15:18 UTC, mildas approved these changes

2022-06-07 15:18 UTC, merged